# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.jvmargs=-Xmx6G --add-opens java.base/java.lang=ALL-UNNAMED
# Mod Info
mod_id=ldlib2
mod_name=LowDragLib2
mod_version=2.0.4
mod_description=Low Drag Lib2, a library for rendering, gui, particles, synchronize
mod_license=GPL-3.0 license
mod_url=https://github.com/Low-Drag-MC/LDLib2
maven_group=com.lowdragmc.ldlib2
minecraft_version=1.20.1
loader_version=0.15.11
yarn_mappings=1.20.1+build.10
fabric_api_version=0.92.1+1.20.1
# Libraries
jei_version=15.8.2.26
rei_version=12.0.652
kjs_version=2001.6.4-build.121
emi_version=1.0.9+1.20.1
ae2_version=15.0.23
yoga_version=1.0.0
iris_version=1.6.9+1.20.1
sodium_version=mc1.20.1-0.5.11
